### ISSUE TITLE
[Victory] Rule is not shown in left panel if active match selected twice or more

### ISSUE THREAD

**Issue by shub1989** [eMoflon/emoflon-ibex-ui#151]
Applying matches is very anonymous, and it has multiple options. Once the rule is updated with previous match and if we click apply match button twice or more for the same rule then it get removed from left panel or gives "ArrayIndexOutOfBound EXception". Output from UI debugger is not consistent.

**Comment by anthonyanjorin** [comment]
@shub1989 Please use the Victory label and add [Victory] to the title of this issue

**Comment by anthonyanjorin** [comment]
What does anonymous mean?
You need to give a TGG and say exactly how to reproduce the exception.

**Comment by anthonyanjorin** [comment]
@LegionaryCohort Please compare with #142 I think the ideas here are related / similar.

**Comment by shub1989** [comment]
As the number of matches are more, it's difficult to select one which will update the next rule and if we select the same match more than once the rule get disappeared from panel or it throws the exception. This may not be the case if i do all the process again. so the outcomes of debugger are not consistent in that manner. and exception is not for same rule all the time it may occur for other rules too if i select matches more than once for those rules or it may not. It would be great if there is some differentiation between rules who has further matches and one which has no matches at all.

**Comment by anthonyanjorin** [comment]
@shub1989 I don't understand your complex explanation at all :(

It's also impossible to reproduce.  I suggest you meet up with @09Ankita or @LegionaryCohort and demonstrate the problem(s) directly on your laptop.

(You still haven't explained what "anonymous" means for you)

**Comment by LegionaryCohort** [comment]
From my understanding of what was shown to me in the meeting, the issue here is as follows:
If the user wants to create the necessary context for a certain rule to match, the matches leading up to that point must be carefully selected from the available matches.
Often the necessary information for selecting the right match must be found in the details of the diagram (e.g. the specific name of an object that requires certain children or something like that). The user currently needs to remember all this information.

As far as I can tell, this issue would be alleviated by completing issues #142, #150 and the naming scheme for matches discussed in #154 
For this reason I'm closing this issue.

@anthonyanjorin If you have any further input on this topic that we should discuss here, feel free to reopen the issue.
