### ISSUE TITLE
[Victory]Total  Rule count

### ISSUE THREAD

**Issue by shub1989** [eMoflon/emoflon-ibex-ui#153]
It would be good to have total rule count for rules that are available in workspace and when we select and apply match, the rule count should get decreased. with every updated rule.

**Comment by anthonyanjorin** [comment]
I don’t understand this (and don’t think it makes much sense to be honest).  Please define „total rule count“.

**Comment by anthonyanjorin** [comment]
@LegionaryCohort Can you perhaps explain what is meant here (I’m curious)?

**Comment by shub1989** [comment]
By "total rule count" i meant to add is, if user knows how to write rule or create meta-models. but if the workspace that he/she  using is new or user don't know exactly how many rules are there in workspace then, 'while using debugger, we don't understand where to stop applying matches. like how one should know that all the rules in workspace are displayed and we don't need to continue further.

**Comment by LegionaryCohort** [comment]
I don't really understand this either.
What problem or use-case is this trying to solve?

**Comment by anthonyanjorin** [comment]
Perhaps some simple statistics:  you have X rules, of which Y are island rules (axioms), Z are bridge rules, and Q are extension rules.

Perhaps also how long it took to initialise? Load all models and rules? Etc?

Just guessing of course, but it might actually be a cool idea to have a dashboard filled with information from the observers Core has already implemented....

**Comment by LegionaryCohort** [comment]
After a short discussion, I've come to understand this Issue as follows:

The problem is that given a user that wants to use the debugger to explore an otherwise unknown project, there is currently no way for the user to know whether he's already seen all the rules the project contains. Especially when rules have a more complex context, it might be that the user never creates a situation that would allow for that rule to be appplied.

As far as I can tell though, this would be solved by #142

**Comment by LegionaryCohort** [comment]
@shub1989 Please confirm that this is what you meant with this issue. If yes, please close, as it is solved by #142
