### ISSUE TITLE
Code completion for imports

### ISSUE THREAD

**Issue by anthonyanjorin** [eMoflon/emoflon-ibex-ui#48]
It should be possible to implement code completion for both the TGG and GT editors.
A scope containing all .ecore files in the workspace would be tremendously helpful.  The user can deal with all other more complex cases.

It would be great to implement this as a kind of Scope-util so it can be shared and used by both editors.

**Comment by patrickrobrecht** [comment]
I already had the same idea, but I dismissed it because a scope defines the set of all possible values I think. So if the scope for imports names is the set of paths to `.*ecore` files in the workspace "all other more complex cases" are forbidden (because those imports would not be in the scope, right?).

But via [Content Assist](https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#content-assist) this should be possible I think.

**Comment by anthonyanjorin** [comment]
hmm...  I understand.  Yes, content assist would be better (if not we would get errors for all other cases).

**Comment by patrickrobrecht** [comment]
I'll try to implement some Content Assist for this. Shall I create a project for common utility functions (such that the editors stay independent, but still can share some utiltity functions)? Other things like loading EClasses from `*.ecore` files could b moved to this editor utility project as well.

**Comment by anthonyanjorin** [comment]
Absolutely!  Also Scope utilities etc.
