### ISSUE TITLE
Inconsistent naming for interfaces

### ISSUE THREAD

**Issue by anthonyanjorin** [eMoflon/emoflon-ibex-ui#66]
The name ```IContextPatternInterpreter``` might sound more intelligent than ```IBlackPatternInterpreter``` but it is a bit problematic as it doesn't fit (conceptually) to ```IGreenPatternInterpreter``` and ```IRedPatternInterpreter```.

**Comment by patrickrobrecht** [comment]
The interfaces for dealing with create and delete patterns in the GT context are called `ICreatePatternInterpreter` and `IDeletePatternInterpreter`, which is consistent with the name `IContextPatternInterpreter` - all placed here: https://github.com/eMoflon/emoflon-ibex/tree/master/org.emoflon.ibex.common/src/org/emoflon/ibex/common/operational

The equivalent interfaces for TGGs are named `IBlackInterpreter` (extending GT's `IContextPatternInterpreter `), `IGreenInterpreter` and `IRedInterpreter`.

The interfaces for create/delete are different for GT and TGG because they deal with different pattern types. For me everything looks fine.

**Comment by anthonyanjorin** [comment]
OK, I wasn’t aware of the consistent switch from „colour“ to „action“.
